### ISSUE TITLE
Config Audio Device.vi crash on MacOS

### ISSUE THREAD

**Issue by ymj120572092** [dataflowg/g-audio#14]
LabVIEW 2021 64 bit Community on MacOS
I want to test playback,but LabVIEW Crash when step into Config Audio Device.vi, I want to test capture but no capture device in my Mac Mini

**Comment by dataflowg** [comment]
Hi @ymj120572092 , thanks for the crash report.

What version of macOS are you using? Is the Mac Mini an Intel or M1 based CPU?

**Comment by ymj120572092** [comment]
> Hi @ymj120572092 , thanks for the crash report.
> 
> What version of macOS are you using? Is the Mac Mini an Intel or M1 based CPU?

**Comment by ymj120572092** [comment]
Hi@dataflowg ,thanks for reply
My Macmini is Intel Core i5,and the version is macOS Sierra 10.12.6,thanks

**Comment by dataflowg** [comment]
Hi @ymj120572092 - apologies for not replying sooner. I've rebuilt the macOS library with an older version of Xcode, and also changed the minimum macOS target to 10.7.

If you used VIPM to install the library, there's a new version v0.4.0 in the [releases section](https://github.com/dataflowg/g-audio/releases/tag/v0.4.0) which you can install.

Otherwise if you're using the source code directly in your project, download the current github repo, then unzip the framework library located at `src/LabVIEW/G-Audio/lib/g_audio_64.framework.zip`.

**Comment by ymj120572092** [comment]
Hi @dataflowg It works after your update
Thank you for your efforts
