### ISSUE TITLE
Feature Request: File Format Recognition

### ISSUE THREAD

**Issue by ItsMeAshiq** [dataflowg/g-audio#3]
Currently the library is checking for the file extension to identify the format.

But in some case an audio file may have a different file extension but the actual data might me of different format.

In this case the library will fail to load the audio file.

So it is better to scan the file headers (signatures) for the File Format details.

Here I have attached an example of implementing it.
![image](https://user-images.githubusercontent.com/87473267/132491954-80716717-b59d-4085-8031-63ef77159631.png)
[Get Codec - copy.zip](https://github.com/dataflowg/g-audio/files/7128032/Get.Codec.-.copy.zip)

This implementation is done in LabVIEW, if it is already available in the dll, it would improve the efficiency (by avoiding opening & closing of file).

File signature details can be found at https://en.wikipedia.org/wiki/List_of_file_signatures

**Comment by dataflowg** [comment]
Thanks for raising this issue, and for the example code and references. It was on my todo list :)

It will probably need to be implemented in the C++ code, so we can open files with unicode paths. In the event those file signatures don't exist (perhaps due to APEv2 tags), the function will fall back to the file extension method.

**Comment by dataflowg** [comment]
File signature detection has been added, and is applied when opening an audio file. A file's codec can also be queried by calling `Get Audio File Info.vi`. Thanks for raising the issue.

**Comment by ItsMeAshiq** [comment]
Nice to have it. Thanks for the update.
